repos:
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo check
        entry: cargo check --all
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-fmt
        name: apply cargo fmt
        entry: cargo fmt
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
